
FPS = 60

NONE = "None"

SWORD = "Sword"
CLAYMORE = "Claymore"
POLEARM = "Polearm"
CATALYST = "Catalyst"
BOW = "Bow"

LIYUE = "Liyue"

ANEMO = "Anemo"
HYDRO = "Hydro"
ELECTRO = "Electro"
DENDRO = "Dendro"
CRYO = "Cryo"
PYRO = "Pyro"
GEO = "Geo"
PHYS = "Physycal"

NA = "Normal Attack"
CA = "Charged Attack"
PA = "Plunge Attack"
SKILL = "Elemental Skill"
BURST = "Elemental Burst"

ATK = "Total ATK"
HP = "Total HP"
DEF = "Total DEF"
ATK_PERCENT = "ATK%"
HP_PERCENT = "HP%"
DEF_PERCENT = "DEF%"
FLAT_ATK = "Flat ATK"
FLAT_HP = "Flat HP"
FLAT_DEF = "Flat DEF"
EM = "Elemental Mastery"
ER = "Energy Recharge"
CD = "CRIT DMG"
CR = "CRIT Rate"
HB = "Healing Bonus"
HR = "Healing Received"
ANEMO_DMG = "Anemo DMG Bonus"
HYDRO_DMG = "Hydro DMG Bonus"
ELECTRO_DMG = "Electro DMG Bonus"
DENDRO_DMG = "Dendro DMG Bonus"
CRYO_DMG = "Cryo DMG Bonus"
PYRO_DMG = "Pyro DMG Bonus"
GEO_DMG = "Geo DMG Bonus"
PHYS_DMG = "Physycal DMG Bonus"